
spring:
  application:
    name: almighty-cloud-backend-application
  boot:
    admin:
      context-path: /admin
      discovery:
        enabled: true
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tom333/config-repo.git
        prefix: config
          

server:
  port: 8080

eureka:
  
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
    
    metadata-map:
      startup: ${random.int}    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
  server:
    port: 8081